export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const GETALL_REQUEST = 'GETALL_REQUEST'
export const GETALL_SUCCESS = 'GETALL_SUCCESS'
export const GETALL_FAILURE = 'GETALL_FAILURE'

export const GET_USER = 'GET_USER'

export const CREATE_SUCCESS ='CREATE_SUCCESS'
export const CREATE_FAILURE ='CREATE_FAILURE'

export const EDIT_SUCCESS ='EDIT_SUCCESS'
export const EDIT_FAILURE='EDIT_FAILURE'

export const DELETE_SUCCESS='DELETE_SUCCESS'